<!DOCTYPE html>
<html>
  <head>
    <meta charset="utf-8">
    <link rel="stylesheet" href="css/app.css">
  </head>
  <body>
      <div class="container">
        @yield('content')
        <footer style="margin-top:3%" class="text-center">Generated by DomPDF</footer>
      </div>

  </body>
</html>